### ISSUE TITLE
Unable to load the dll

### ISSUE THREAD

**Issue by wir3z** [kavejo/TransportAgents#1]
Excited to try this, but running into issues loading the DLL.  I'm using Exchange 2019 CU14, and it has .NET 4.8 installed.  I was using the tagged dll and also tried to compile it but both do the same.

When I call this:
Install-TransportAgent -Name DomainReroutingAgent -TransportAgentFactory "TransportAgents.DomainReroutingAgent" -AssemblyPath "C:\TransportAgents\TransportAgents.dll"

I get this error:
Could not load file or assembly 'file:///C:\TransportAgents\TransportAgents.dll' or one of its dependencies. Operation
is not supported. (Exception from HRESULT: 0x80131515)
    + CategoryInfo          : InvalidArgument: (:) [Install-TransportAgent], FileLoadException

Any idea on what I need to look at to get this to load?

**Comment by kavejo** [comment]
Hi @wir3z,

Can you please verify that "Exchange Trusted Subsystem" and "Exchange Servers" have permissions on the folder C:\TransportAgents, like shown below (in the screenshot it's the F:\TransportAgents folder)?

![image](https://github.com/user-attachments/assets/90b3146f-221d-408b-9d24-e0dc56df9449)

**Comment by wir3z** [comment]
Thanks!  That was the issue.  I had to:
- add those two users
- reboot the server
- install the dll

Thanks for posting these examples for the transport agents.  It works great.
